MAINAPP/urls.py
from django.urls import path
from . import views
from . import chatbot
from django.contrib.auth import views as auth_views

urlpatterns = [
	#Leave as empty string for base url
	path('', views.home, name="home"),
	path('register/', views.register,name='register'),
	path('registerasexpert/', views.registerasexpert,name='registerasexpert'),
	path('user_login/', views.user_login,name='user_login'),
	path('logout/', views.user_logout,name='logout'),
	path('diabetes_risk/', views.diabetes_risk,name='diabetes_risk'),
	path('diabetes_risk_result/', views.diabetes_risk_result,name='diabetes_risk_result'),
	path('cvd_prediction/', views.cvd_prediction,name='cvd_prediction'),
	path('cvd_prediction_result/', views.cvd_prediction_result,name='cvd_prediction_result'),
	path('detect_brain_tumor/', views.detect_brain_tumor,name='detect_brain_tumor'),
	path('detect_brain_tumor_result/', views.detect_brain_tumor_result,name='detect_brain_tumor_result'),
	path('liver_diagnosis/', views.liver_diagnosis,name='liver_diagnosis'),
	path('liver_diagnosis_result/', views.liver_diagnosis_result,name='liver_diagnosis_result'),
	path('diagnosistools/', views.diagnosistools,name='diagnosistools'),
	path('healthcheckup/', views.symptomsdiagnosis,name='healthcheckup'),
	path('healthcheckup_result/', views.symptomsdiagnosis_result,name='healthcheckup_result'),
	path('article/', views.article,name='article'),
	path('<int:id>/read_article/', views.read_article, name="read_article"),
	path('mentalhealth/', views.mentalhealth,name='mentalhealth'),
	path('mentalhealth_results/', views.mentalhealth_results,name='mentalhealth_results'),
	path('diet_plan/', views.diet_plan,name='diet_plan'),
	path('diet_plan_result/', views.diet_plan_result,name='diet_plan_result'),
    path('ASDdiagnosis/', views.ASDdiagnosis,name='ASDdiagnosis'),
    path('ASDdiagnosis_result/', views.ASDdiagnosis_result,name='ASDdiagnosis_result'),
	path('search/', views.search,name='search'),
	path('about/', views.about,name='about'),
	path('accounts/', views.accounts,name='accounts'),
	path('rating/', views.rating,name='rating'),
	path('report/', views.report,name='report'),
	path('healthcareexperts/', views.healthcareexperts,name='healthcareexperts'),
	path('<int:id>/appointment/', views.appointment, name="appointment"),
	path('create_medical_profile/', views.create_medical_profile,name='create_medical_profile'),
	path('<int:id>/update_medical_profile/', views.update_medical_profile,name='update_medical_profile'),
	path('404/',views.page_not_found),
	path('reset_password/', auth_views.PasswordResetView.as_view(template_name='MAINAPP/password_reset.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='MAINAPP/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='MAINAPP/password_reset_form.html'), name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(template_name='MAINAPP/password_reset_complete.html'), name='password_reset_complete'),
	path('medical_chatbot/', chatbot.medical_chatbot, name='medical_chatbot'),
    ]

PROJECT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MAINAPP.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404="MAINAPP.views.page_not_found"

MAINAPP/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import TextField
from django.utils import timezone

# Create your models here.
class Disease(models.Model):
	posted_on=models.DateField(blank=True,default=timezone.now)
	disease_name = models.CharField(max_length= 200)
	disease_caption=models.TextField(blank=True)
	disease_description=models.TextField(blank=True)
	disease_symptoms =models.TextField(blank=True)
	disease_precautions =models.TextField(blank=True)
	disease_medication =models.TextField(blank=True)
	disease_image = models.ImageField(null=True, blank=True , help_text="crop image as square before upload to get uniform size in the page")
	add_disease_to_home = models.BooleanField(default=False,null=True, blank=True ,help_text="Yes will enable to display it on home page")
	def __str__(self):
		return self.disease_name

	@property
	def disease_imageURL(self):
		try:
			url = self.disease_image.url
		except:
			url = ''
		return url


class Helpline(models.Model):
	organization=models.CharField(max_length= 500)
	country = models.CharField(max_length= 500)
	helpline_number=models.CharField(max_length= 500)
	organization_details =models.TextField(blank=True)
	def __str__(self):
		return self.organization


class ContactMessage(models.Model):
	reviewer_name = models.CharField(max_length= 200 ,blank=True)
	reviewer_email=models.EmailField(max_length =200 ,blank=True)
	reviewer_message = models.TextField(max_length=5000,blank=True)

	def __str__(self):
		return self.reviewer_name

class DiagnosisTool(models.Model):
	tool_name = models.CharField(max_length= 200 ,blank=False)
	tool_accuracy = models.CharField(max_length= 200 ,blank=False)
	tool_technology = models.CharField(max_length= 200 ,blank=False)
	tool_detail = models.TextField(max_length=4000,blank=False)
	tool_link = models.CharField(max_length= 200 ,blank=False)
	def __str__(self):
		return self.tool_name

class Food(models.Model):
	food_name = models.CharField(max_length= 300)
	diet_category = models.CharField(max_length= 100 ,blank=False)
	diabetic = models.BooleanField(default=False,null=True, blank=True)
	veg_food = models.BooleanField(default=True,null=True, blank=True)
	Calories = models.CharField(max_length= 100 ,blank=False)
	Fats = models.CharField(max_length= 100 ,blank=False)
	Proteins = models.CharField(max_length= 100 ,blank=False)
	Iron = models.CharField(max_length= 100 ,blank=False)
	Calcium = models.CharField(max_length= 100 ,blank=False)
	Sodium = models.CharField(max_length= 100 ,blank=False)
	Potassium= models.CharField(max_length= 100 ,blank=False)
	Carb = models.CharField(max_length= 100 ,blank=False)
	Fibres = models.CharField(max_length= 100 ,blank=False)
	Sugars = models.CharField(max_length= 100 ,blank=False)

	def __str__(self):
		return self.food_name


class Rating(models.Model):
	rating_user = models.CharField(max_length= 300 ,blank=True)
	rating_tool=models.CharField(max_length =300 ,blank=True)
	rating_parameter=models.CharField(max_length =100 ,blank=True)
	rating_message = models.TextField(blank=True)
	rating_time=models.DateField(blank=True,default=timezone.now)

	def __str__(self):
		return self.rating_user


class DiabetesDiagnosisHistory(models.Model):
	username=models.CharField(max_length= 300 ,blank=True)
	Pregnancies=models.CharField(max_length= 300 ,blank=True)
	Glucose=models.CharField(max_length= 300 ,blank=True)
	BloodPressure=models.CharField(max_length= 300 ,blank=True)
	SkinThickness=models.CharField(max_length= 300 ,blank=True)
	Insulin=models.CharField(max_length= 300 ,blank=True)
	BMI=models.CharField(max_length= 300 ,blank=True)
	DiabetesPedigreeFunction=models.CharField(max_length= 300 ,blank=True)
	Age=models.CharField(max_length= 300 ,blank=True)
	outcome=models.CharField(max_length= 300 ,blank=True)
	risk_score=models.CharField(max_length= 300 ,blank=True)
	Diagnosis_Date=models.DateField(blank=True,default=timezone.now)
	def __str__(self):
		return self.username


class HeartDiseaseDiagnosisHistory(models.Model):
	username=models.CharField(max_length= 300 ,blank=True)
	age=models.CharField(max_length= 300 ,blank=True)
	sex=models.CharField(max_length= 300 ,blank=True)
	cp=models.CharField(max_length= 300 ,blank=True)
	trestbps=models.CharField(max_length= 300 ,blank=True)
	chol=models.CharField(max_length= 300 ,blank=True)
	fbs=models.CharField(max_length= 300 ,blank=True)
	restecg=models.CharField(max_length= 300 ,blank=True)
	thalach=models.CharField(max_length= 300 ,blank=True)
	exang=models.CharField(max_length= 300 ,blank=True)
	oldpeak=models.CharField(max_length= 300 ,blank=True)
	slope=models.CharField(max_length= 300 ,blank=True)
	outcome=models.CharField(max_length= 300 ,blank=True)
	risk_score=models.CharField(max_length= 300 ,blank=True)
	Diagnosis_Date=models.DateField(blank=True,default=timezone.now)
	def __str__(self):
		return self.username

class LiverDiseaseDiagnosisHistory(models.Model):
	username=models.CharField(max_length= 300 ,blank=True)
	Age=models.CharField(max_length= 300 ,blank=True)
	Gender=models.CharField(max_length= 300 ,blank=True)
	Total_Bilirubin=models.CharField(max_length= 300 ,blank=True)
	Direct_Bilirubin=models.CharField(max_length= 300 ,blank=True)
	Alkaline_Phosphotase=models.CharField(max_length= 300 ,blank=True)
	Alamine_Aminotransferase=models.CharField(max_length= 300 ,blank=True)
	Aspartate_Aminotransferase=models.CharField(max_length= 300 ,blank=True)
	Total_Protiens=models.CharField(max_length= 300 ,blank=True)
	Albumin=models.CharField(max_length= 300 ,blank=True)
	Albumin_and_Globulin_Ratio=models.CharField(max_length= 300 ,blank=True)
	outcome=models.CharField(max_length= 300 ,blank=True)
	risk_score=models.CharField(max_length= 300 ,blank=True)
	Diagnosis_Date=models.DateField(blank=True,default=timezone.now)
	def __str__(self):
		return self.username

class BrainTumorDiagnosisHistory(models.Model):
	username=models.CharField(max_length= 300 ,blank=True)
	Mean=models.CharField(max_length= 300 ,blank=True)
	Variance=models.CharField(max_length= 300 ,blank=True)
	StandardDeviation=models.CharField(max_length= 300 ,blank=True)
	Entropy=models.CharField(max_length= 300 ,blank=True)
	Skewness=models.CharField(max_length= 300 ,blank=True)
	Kurtosis=models.CharField(max_length= 300 ,blank=True)
	Contrast=models.CharField(max_length= 300 ,blank=True)
	Energy=models.CharField(max_length= 300 ,blank=True)
	ASM=models.CharField(max_length= 300 ,blank=True)
	Homogeneity=models.CharField(max_length= 300 ,blank=True)
	Dissimilarity=models.CharField(max_length= 300 ,blank=True)
	Correlation=models.CharField(max_length= 300 ,blank=True)
	Coarseness=models.CharField(max_length= 300 ,blank=True)
	PSNR=models.CharField(max_length= 300 ,blank=True)
	SSIM=models.CharField(max_length= 300 ,blank=True)
	MSE=models.CharField(max_length= 300 ,blank=True)
	DC=models.CharField(max_length= 300 ,blank=True)
	outcome=models.CharField(max_length= 300 ,blank=True)
	risk_score=models.CharField(max_length= 300 ,blank=True)
	Diagnosis_Date=models.DateField(blank=True,default=timezone.now)
	def __str__(self):
		return self.username

class Bug(models.Model):
	reported_on=models.DateField(blank=True,default=timezone.now)
	problem = models.CharField(max_length= 200)
	problem_description=models.TextField(blank=True)

	problem_image = models.ImageField(null=True, blank=True)
	def __str__(self):
		return self.problem

	@property
	def problem_imageURL(self):
		try:
			url = self.problem_image.url
		except:
			url = ''
		return url


class HealthcareExpert(models.Model):

	expert_username = models.CharField(max_length= 1000)
	expert_name = models.CharField(max_length= 1000, blank=True)
	expert_email = models.CharField(max_length= 1000,blank=True)
	expert_designation= models.CharField(max_length= 2000)
	expert_specialization= models.CharField(max_length= 4000)
	expert_address= models.CharField(max_length= 4000)
	expert_contact= models.CharField(max_length= 1000)
	expert_image = models.ImageField(null=True, blank=True)
	def __str__(self):
		return self.expert_username

	@property
	def expert_imageURL(self):
		try:
			url = self.expert_image.url
		except:
			url = ''
		return url


class Appointment(models.Model):
	booked_on=models.DateField(blank=True,default=timezone.now)
	preferred_date=models.DateField(blank=True,default=timezone.now)
	booked_by = models.CharField(max_length= 1000)
	user_email = models.CharField(max_length= 1000)
	expert_username = models.CharField(max_length= 1000)
	expert_email = models.CharField(max_length= 1000)
	problem =models.TextField(blank=False)
	accepted = models.BooleanField(default=False,null=True, blank=True)
	def __str__(self):
		return self.booked_by


class MedicalProfile(models.Model):
	username = models.CharField(max_length= 1000)
	updated_on=models.DateField(blank=True,default=timezone.now)
	age = models.CharField(max_length= 100, blank=True)
	gender = models.CharField(max_length= 100, blank=True)
	blood_group = models.CharField(max_length= 100, blank=True)
	height = models.CharField(max_length= 100, blank=True)
	weight = models.CharField(max_length= 100, blank=True)
	emergency_contact = models.CharField(max_length= 100, blank=True)
	diabetic = models.BooleanField(default=False,null=True, blank=True)
	def __str__(self):
		return self.username

MAINAPP/forms.py
from django import forms
from django.contrib.auth.models import User
from MAINAPP.models import *

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('first_name','last_name','username', 'email' , 'password')

class ContactMessageForm(forms.ModelForm):
    class Meta():
        model =  ContactMessage
        fields =('reviewer_name','reviewer_email','reviewer_message',)

class ReportForm(forms.ModelForm):
    class Meta():
        model = Bug
        fields =('reported_on','problem','problem_description','problem_image',)

class MedicalProfileUpdateForm(forms.ModelForm):
    class Meta():
        model = MedicalProfile
        fields =('updated_on','age','gender','blood_group','height','weight','emergency_contact','diabetic')

templates/MAINAPP/appointment.html
{%  extends 'MAINAPP/home.html' %}
{% load static %}
{% block content %}
<br><br>
<div class="container col-lg-9">
  <p style="font-size:22px;color:black;font-weight:400;font-family: 'Roboto', sans-serif;margin-bottom:2px;text-align:center;" >Book an Appointment</p>
  <br>
  <div class="row">
    <div class="col-lg-4" style="margin-left:auto;margin-right:auto;display:flex;flex-wrap:wrap;padding:20px;">
      <div class="" style="width:100%;width:100%;border-radius:15px;border:1px solid #CACFD2;padding:10px;">
        <div class="text-center">
          <img class="sharp"src="{{ expert.expert_imageURL }}"  style="width:140px;padding:5px;border-radius:300px;width:50%" >
        </div>
        <div class="" style="background:#F8F9F9;padding:20px 20px 10px 20px;margin-top:-70px;border-radius:0px 0px 10px 10px ">
          <p style="margin-bottom:70px;"></p>
          <p style="margin:3px;font-size:14px;font-weight:500;color:black;font-family: 'Roboto', sans-serif;text-align:center">{{expert.expert_name}}</p>
             <hr>
          <div class="text-center">
            <label ><a href="tel:{{ expert.expert_contact }}"><i class="bi bi-telephone-fill" style="margin:5px;font-size:16px;"></i></a></label>
           <label ><a href="mailto:{{ expert.expert_email }}"><i class="bi bi-envelope" style="margin:5px;font-size:18px;"></i></a></label>
          </div>

          <p style="font-size:12px;margin:0px;font-weight:800;color:black;font-family: 'Roboto', sans-serif;"><i class="bi bi-geo-alt-fill"></i> Location  </p>
          <p style="font-size:11px;font-weight:400;color:gray;font-family: 'Roboto', sans-serif;"> {{expert.expert_address}}</p>
          <p style="font-size:12px;margin:0px;font-weight:800;color:black;font-family: 'Roboto', sans-serif;"><i class="bi bi-bag-plus-fill"></i> Designation  </p>
          <p style="font-size:11px;font-weight:400;color:gray;font-family: 'Roboto', sans-serif;"> {{expert.expert_designation}}</p>
          <p style="font-size:12px;margin:0px;font-weight:800;color:black;font-family: 'Roboto', sans-serif;"><i class="bi bi-tools"></i> Specialization </p>
          <p style="font-size:11px;font-weight:400;color:gray;font-family: 'Roboto', sans-serif;"> {{expert.expert_specialization}}</p>
       </div>
      </div>
    </div>
    <div class="col-lg-6" style="margin-left:auto;margin-right:auto;display:flex;flex-wrap:wrap;padding:20px;">
      <div class="" style="width:100%;padding:0px;">
        <form class=""  method="POST" enctype="multipart/form-data" action ="{% url 'appointment' expert.id %}">
          {% csrf_token %}
          <input  placeholder="Enter Your Name"type="text" class="form-control" id ="id_booked_by" name="booked_by"  style="border:1px solid #CACFD2;border-radius:50px;font-size:13px;color:black;font-weight:400;margin-bottom:20px;" required>
          <input placeholder="Enter Your Email Address"type="email" class="form-control" id ="id_user_email"name="user_email"  style="border:1px solid #CACFD2;border-radius:50px;font-size:13px;color:black;font-weight:400;margin-bottom:10px;" required>

          <label for="id_problem" style="font-size:13px;font-weight:700;margin:5px;color:black;">Appointment Note / Problem</label>
          <div class="text-center">
          <textarea class="form-control" name="problem"  id="id_problem" style="width:100%;height:70px;font-size:12px;padding:10px;resize: none;border-radius:10px;" required></textarea>
          </div>
          <br>
          <label style="font-size:13px;font-weight:700;margin:5px;color:black;">Preferred Date</label>
          <input type="date" class="form-control" id="date" value="{{placement.date|date:"Y-m-d" }}"  name="preferred_date" required>
          <br>
          {% for message in messages %}
            <p style="text-align:center;color:green;font-size:13px">{{message}}</p>
          {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-outline-primary" style="border-radius:50px;font-weight:400;font-size:14px;border-width:1px;padding:4px 12px 4px 12px">Book Now <i class="bi bi-chevron-double-right"></i> </button>
          </div>
          </form>
      </div>
    </div>
  </div>

</div>
<br><br>

{% endblock content %}

templates/MAINAPP/article.html
{%  extends 'MAINAPP/home.html' %}
{% load static %}
{% block content %}
<!--background-image:url({% static 'images/gradient1.png'%}); FOR BACKGROUND IMAGE-->
<div class="articlebg"style="background-color:rgba(0,0,0,0.93);"  >

<div class="container bground1" >
<br><br>
<p  style="font-size:28px;font-weight:600;font-family: 'Roboto', sans-serif;text-align :center;margin:0px;color:white">MediTrack Reads</p>

<p  style="margin-left:auto;margin-right:auto;font-size:13px;font-weight:400;font-family: 'Roboto', sans-serif;text-align :center;color:white" >The Healthcare reads with a healthy dose of updates. </p>
<br>
  <div class="col-lg-10 col-md-12 col-sm-12  col-12" style="margin-left:auto;margin-right:auto;padding:15px;"data-aos="zoom-in">

    <div class="row">
        {% for page in pages %}
        <div class="col-lg-3 col-md-4 col-sm-6 col-12" style="margin-left:auto;margin-right:auto;display:flex;flex-wrap:wrap;padding:10px;">
          <div class=" flipcard" style="margin:0px;padding:5px;border-radius:20px;border:1px solid #CACFD2;">
             <div class="flipcard-wrap"  >
               <div class="card card-front" style="width:100%;background:black;border-radius:15px;">
                    <div class="card-body" style="padding:20px;">
                   <p style="text-align:center;font-size:14px;color:white;font-weight:600;margin:0px;">{{ page.disease_name}}</p>
                   <p style="text-align:center;font-size:11px;color:#BFC9CA;">Posted on. {{ page.posted_on}}</p>
                   <img src="{{ page.disease_imageURL }}"  style="width:100%;padding:5px;border-radius:15px;" >
                   </div>
                </div>
                <div class="card card-back" style="background:black;">
                  <div class="card-body" style="padding:15px;">
                    <p style="text-align:center;font-size:11px;color:#BFC9CA;">{{ page.disease_caption}}</p>
                    <a class="btn btn-outline-primary"data-product="{{ page.id }}"  href="{% url 'read_article' page.id %}" style="border-radius:30px;border-width:2px;font-size:14px;margin:auto;font-weight:700;">Read <i class="bi bi-chevron-double-right"></i></a>
                  </div>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}
     </div>

  </div>
  <br><br>
</div>
</div>
{% endblock content %}

templates/MAINAPP/create_medical_profile.html
{%  extends 'MAINAPP/home.html' %}
{% load static %}
{% block content %}
<br><br>
<div class="bground1 container">
{% if user.is_authenticated %}
{% if created %}
<br><br>
<div class="text-center" style="padding:5%;padding-bottom:10%">
<p style="font-size:15px;font-weight:600;color:black;font-family: 'Roboto', sans-serif;text-align:center;margin:10px;" >Medical Profile Already Exist</p>
</div>
<br><br>
{% else  %}
<div class="container col-lg-10" style="padding:5%;box-shadow:0px 0px 25px 0px rgba(0, 0, 0,0.15);">
  <div class="text-center">
    <p style="font-size:22px;font-weight:500;color:black;font-family: 'Roboto', sans-serif;text-align:center;margin:10px;" >Medical Profile</p>
    <hr>
  </div>
  <form class=""  method="POST" enctype="multipart/form-data" action ="{% url 'create_medical_profile' %}">
    {% csrf_token %}
    <div class="row">
      <div class="col-lg-6" style="padding:20px;">
        <label for="gender" style="font-size:14px;color:black;font-weight:700;margin:4px;">Gender</label>
        <div class="" style="background:white;padding:5px;padding-bottom:15px;">
        <div class="form-check">
        <input class="form-check-input" value="Male" type="radio" name="gender" id="male"checked >
        <label style="font-size:13px;color:#566573 ;font-weight:400;"class="form-check-label"  for="male">Male</label>
        <br>
        <input class="form-check-input" value="Female" type="radio" name="gender" id="female" >
        <label style="font-size:13px;color:#566573 ;font-weight:400;" class="form-check-label" for="female">Female</label>
        </div>
        </div>

        <label for="id_age" style="font-size:13px;font-weight:700;margin:5px;color:black;">Age</label>
        <input type="text" class="form-control" id ="id_age" name="age"  style="border:1px solid #CACFD2;border-radius:50px;font-size:13px;color:black;font-weight:500;margin-bottom:10px;" required>
        <label for="id_blood_group" style="font-size:13px;font-weight:700;margin:5px;color:black;">Blood Group</label>
        <input type="text" class="form-control" id ="id_blood_group" name="blood_group"  style="border:1px solid #CACFD2;border-radius:50px;font-size:13px;color:black;font-weight:500;margin-bottom:10px;" required>
      </div>
      <div class="col-lg-6" style="padding:20px;">
        <input type="text" class="form-control"name="height" placeholder="Enter height in meter" style=" background:#E5E7E9;border:0px;border-radius:50px;padding:18px;font-size:13px;color:black;margin-bottom:12px;" required>
        <input type="text" class="form-control"name="weight" placeholder="Enter weight in kg" style=" background:#E5E7E9;border:0px;border-radius:50px;padding:18px;font-size:13px;color:black;margin-bottom:12px;" required>
        <label for="id_emergency_contact" style="font-size:13px;font-weight:700;margin:5px;color:black;">Emergency Contact</label>
        <input type="text" class="form-control" id ="id_emergency_contact" name="emergency_contact"  style="border:1px solid #CACFD2;border-radius:50px;font-size:13px;color:black;font-weight:500;margin-bottom:10px;" required>

        <label for="diabetic" style="font-size:14px;color:black;font-weight:700;margin:4px;">Diabetic</label>
        <div class="" style="background:white;padding:5px;">
        <div class="form-check">
        <input class="form-check-input" value="False" type="radio" name="diabetic" id="Dno"checked >
        <label style="font-size:13px;color:#566573 ;font-weight:400;"class="form-check-label"  for="Dno">No</label>
        <br>
        <input class="form-check-input" value="True" type="radio" name="diabetic" id="Dyes" >
        <label style="font-size:13px;color:#566573 ;font-weight:400;" class="form-check-label" for="Dyes">Yes</label>
        </div>
      </div>

      </div>
    </div>

    {% for message in messages %}
      <p style="text-align:center;color:green;font-size:13px">{{message}}</p>
    {% endfor %}
    <div class="text-center">
      <button type="submit" class="btn btn-primary" style="border-radius:50px;font-weight:500;font-size:15px;border-width:1px;padding:4px 12px 4px 12px">Create <i class="bi bi-chevron-double-right"></i> </button>
    </div>
    </form>

</div>
<br><br>

{% endif %}

{% else %}
<br><br>
<div class="text-center" style="padding:5%;padding-bottom:15%">
<p style="font-size:18px;font-weight:600;color:black;font-family: 'Roboto', sans-serif;text-align:center;margin:10px;" >User not logged In</p>

<p style="font-size:12px;color:#626567;">Please login to access your account and create your <br>medical profile.</p>
<a class="btn btn-outline-primary" href="{% url 'user_login' %}" style="border-radius:30px;border-width:2px;font-size:16px;margin:auto;font-weight:600">Log In</a>
</div>
<br><br>
{% endif %}

</div>

{% endblock content %}

templates/MAINAPP/password_reset.html
{%  extends 'MAINAPP/home.html' %}
{% load static %}
{% block content %}
<div class="">
<br><br>
<div class="container" style="padding-bottom:150px;">
  <div class="row">

    <div class="col-lg-6 col-md-9 col-sm-12 col-12" style="margin-left:auto;margin-right:auto;display:flex;flex-wrap:wrap;">
      <div class="" style="width:100%;padding:5%">
        <p style="font-size:40px;color:black;text-align:center">Reset Password</p>
        <hr color="#CACFD2" style="margin:10px;margin-bottom:20px;">
        <p style="font-size:13px;text-align:center;color:#626567">Please write the <b>registered email </b>
        which is linked to your account to reset the password.</p>

        <form method="post">
          {% csrf_token %}

          <div style="padding:20px;">
            <p style="font-size:14px;font-weight:600;">Email Address</p>
          <input type="email" class="form-control"name="email"  style="background:#E5E7E9;border-width:0px;font-size:14px;border-radius:30px;" required>
          </div>
          <br>
          <div class="text-center">
          <input type="submit" class="btn btn-outline-primary text-center"
          href="templates/MAINAPP/password_reset_sent.html"value=" Send reset link " style="font-size:15px;border-radius:40px;border-width:2px;font-weight:600;">
          </div>
        </form>


      </div>
    </div>
  </div>
</div>
</div>

{% endblock content %}